language: python

python:
  - 3.7
  - 3.8
  - 3.9

addons:

install:
  - pip install -r requirements.txt
  - pip install celery

script:
  - cd tests/eufrates
  - coverage run --source=eufrates -m unittest discover -v . "*Test.py"
  - coverage xml -i
  - cd ../..

after_success:

git:
  depth: false

jobs:
  include:
  - python: 3.7
  - python: 3.8
  - python: 3.9
    env: RUN_QUALITY_GATES=true
